const ShopActionTypes = {
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
  FETCH_COLLECTION: "FETCH_COLLECTION",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_ERROR: "FETCH_COLLECTION_ERROR",
    
};

export default ShopActionTypes;
